### ISSUE TITLE
PHD.yuying 你好，可以分享一下您在论文中报道的模型吗？

### ISSUE THREAD

**Issue by MedicalkodeFish** [yuyingliu-1/EndoDepth-estimation#1]
我是一名消化内科的医生，因为没有高性能GPU，所以期待能够开源模型。我一直在寻找可以将内镜影像进行重建的方法，因为这可以帮助患者评估病情或检测病变，特别是病变大小的检测、病变良恶性的判断和提高病变的检出率。我认为您的研究对未来胃肠道内镜诊断的发展是有裨益的。我去试用了Endo-SfMLearner，也看了您的文献，仍有些技术问题不明白，例如怎么将深度图转化为点云图，怎么用多张图像生成胃肠道的重建等。如果您也有兴趣的话，期待能与您合作，让您的研究成果能够真正帮助医生和患者。希望您能回复我。谢谢！

**Comment by yuyingliu-1** [comment]
首先感谢您的关注。有关模型的开源数据，我们正在整理，涉及相关项目进程可能稍微推迟（有可能会给出两个版本，这个版本侧重点在于如何更好的得到深度信息，后续的工作会涉及如何更好的进行重建）。关于您提到的重建问题，您可以了解一下TSDF技术，我们验证过效果还可以。另一方面，RGB图像重建用于导航更实用，在这个过程中可以结合分割识别等任务完成病变检测。如果您有更为详细的疑问可以进一步提出，我很乐意为您解答。

**Comment by MedicalkodeFish** [comment]
谢谢您的回复，我注意到内镜图片中的反射光斑会对深度估计产生较大影响，不知道您是否有去光斑或者是避免这一影响的方法

**Comment by MedicalkodeFish** [comment]
另外我这里有一些内镜影像资料，不知是否对您研究有帮助，如您需要我可以分享给您

**Comment by 303Sally** [comment]
您好，去光斑的方法可以参考论文：“Self-Supervised monocular depth and ego-Motion estimation in endoscopy: Appearance flow to the rescue”里的方法，我想知道关于相机参数的问题，一般结肠镜使用的鱼眼相机等全景相机会产生变形，不满足针孔相机的内参条件，请问这一问题是如何解决的？

**Comment by yuyingliu-1** [comment]
> 您好，去光斑的方法可以参考论文：“Self-Supervised monocular depth and ego-Motion estimation in endoscopy: Appearance flow to the rescue”里的方法，我想知道关于相机参数的问题，一般结肠镜使用的鱼眼相机等全景相机会产生变形，不满足针孔相机的内参条件，请问这一问题是如何解决的？
论文中训练模型用的两个数据集都是非临床数据，如果考虑到临床数据中的实际问题，这篇文章Neural ray surfaces for self-supervised learning of depth and ego-motion或许对你有帮助。

**Comment by 303Sally** [comment]
> > 您好，去光斑的方法可以参考论文：“Self-Supervised monocular depth and ego-Motion estimation in endoscopy: Appearance flow to the rescue”里的方法，我想知道关于相机参数的问题，一般结肠镜使用的鱼眼相机等全景相机会产生变形，不满足针孔相机的内参条件，请问这一问题是如何解决的？
> > 论文中训练模型用的两个数据集都是非临床数据，如果考虑到临床数据中的实际问题，这篇文章Neural ray surfaces for self-supervised learning of depth and ego-motion或许对你有帮助。

非常感谢！
